### ISSUE TITLE
Resuming broken with mod_rename

### ISSUE THREAD

**Issue by benrubson** [Castaglia/proftpd-mod_rename#2]
Hello,

This bug report follows ProFTPd bug #4008 :
http://bugs.proftpd.org/show_bug.cgi?id=4008

As explained in bug 4008, I use the following configuration :
RenameEngine            on
<Directory />
RenamePrefix \#. max 0
</Directory>

When I upload a file that already exists, if I want to simply replace it, file
is replaced, perfect.

However, let's assume I want to resume a broken file transfer.
In this case, resume will not work as destination file will be deleted first by
mod_rename.
FTP server will then return 550 No such file or directory.

Could it be possible to have mod_rename "disabled" when a file transfer is
resumed ?
I think that it should be the right behavior to go with.

Thank you very much !

Best regards,

Ben

**Comment by benrubson** [comment]
I just saw that TJ corrected this bug :
http://bugs.proftpd.org/show_bug.cgi?id=4183

Thank you very much TJ !

**Comment by jschvartz** [comment]
Thanks, I was waiting for that too.
Will try and feed back any problem.
Thanks again for all the work, TJ.
